### ISSUE TITLE
White Screen

### ISSUE THREAD

**Issue by Tacobello** [skynet-Inc/Discord-Lite#29]
**Only White Screen**
Hello I recently started using your program and it worked well at the start.
But recently I am only getting white screen.
I have restarted the pc many times.
Uninstalled and re-installed the program.
But always getting the same white screen.
Maybe is there something I can do to fix this issue?
thank you

![Discord lite issue](https://user-images.githubusercontent.com/83551423/202016876-5a1a31c9-7678-4a16-b6c4-41ecc36c30b9.jpg)

**Comment by therealcyber71** [comment]
The issue has been solved?

**Comment by Tacobello** [comment]
Not yet but I saw one threat on the page  referring to WebView2
so gonna try that first thank you^^

**Comment by therealcyber71** [comment]
Coolio
