### ISSUE TITLE
Virustotal flags discord lite as malicious

### ISSUE THREAD

**Issue by lemon8de** [skynet-Inc/Discord-Lite#31]
![image](https://user-images.githubusercontent.com/113398979/202974077-ebb652b3-2c1e-4eb5-8a74-02a972c1e9db.png)

I ran a quick scan of my computer using Process Explorer (sys internals) and I got results from discord lite. Most notably a clear flag of a trojan and a backdoor.

**Comment by therealcyber71** [comment]
Check closed issues, also if you don't trust the binary provided, build from source, if you still aren't satisfied, don't install it at all 👍

**Comment by therealcyber71** [comment]
It's called a false positive btw

**Comment by therealcyber71** [comment]
Please let me know if the issue has been solved 👍

**Comment by therealcyber71** [comment]
Since it's apparently very hard for you to find closed issues, https://github.com/skynet-Inc/Discord-Lite/issues/15

**Comment by therealcyber71** [comment]
Will be closing the issue.
